name: gamevault

services:
  postgres:
    image: postgres:18-alpine3.22
    restart: unless-stopped
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
      - postgres-data:/var/lib/postgresql/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      interval: 30s
      timeout: 5s
      retries: 3
      test: ["CMD-SHELL", "pg_isready -U postgres"]
    networks:
      - gamevault-net

networks:
  gamevault-net:
    driver: bridge

volumes:
  postgres-data: